runtime: nodejs10

service: nodejs-todo

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

automatic_scaling:
  max_instances: 1

includes:
  - env_variables.yaml